version: '3'

services:
  rabbitmq:
    image: "rabbitmq:management"  # используем образ с включенным управлением
    hostname: rabbitmqhost
    restart: always
    ports:
      - "5672:5672"  # порт для AMQP
      - "15672:15672"  # порт для управляющего интерфейса
    volumes:
      - /var/lib/rabbitmq  # сохраняем данные на диске
    environment:
      - RABBITMQ_DEFAULT_USER=livmq  # имя пользователя
      - RABBITMQ_DEFAULT_PASS=livmq  # пароль
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 1431655766  # 1.3 Gib